runtime! debian.vim
syntax on
colorscheme desert
set formatoptions-=o  " Disable automatic comment continuation
set noautoindent
set nocindent
set nocompatible
set nocursorline
set nomodeline
set nosmartindent    
set nottyfast
set nosmartindent
set backspace=indent,eol,start
set indentexpr=
set mouse=r
set ruler
set scroll=25
set ttymouse=sgr
set redrawtime=10000
